---
- name: Create Mount-directories
  ansible.builtin.file:
    path: "{{ item.mountpoint }}"
    state: directory
    # owner: "{{ item.owner | default('root') }}"
    # group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0770') }}"
  become: yes
  with_items: 
    - "{{ filesystems }}"
  when:
    - filesystems is defined

- name: Mount Filesystems
  ansible.posix.mount:
    path:   "{{ item.mountpoint }}"
    src:    "{{ item.device }}"
    fstype: "{{ item.fstype | default('ext4') }}"
    state:  mounted
  become: yes
  with_items: 
    - "{{ filesystems }}"
  when:
    - filesystems is defined

# - name: Change file ownership, group and permissions
#   ansible.builtin.file:
#     path: "{{ item.mountpoint }}"
#     owner: "{{ item.owner | default('root') }}"
#     group: "{{ item.group | default('root') }}"
#     mode: "{{ item.mode | default('0770') }}"
#   become: yes
#   with_items: 
#     - "{{ filesystems }}"
#   when:
#     - filesystems is defined
